from dataclasses import dataclass, field
from datetime import datetime, timedelta
import hashlib
from urllib.parse import quote
from typing import Callable, Literal

from app.core.config import settings
from app.scrapers.funda import fetch_funda_listings
from app.scrapers.generic_sources import (
    GenericSourceConfig,
    fetch_generic_source_listings,
)
from app.scrapers.ikwilhuren import fetch_ikwilhuren_listings
from app.scrapers.marktplaats import fetch_marktplaats_listings


FetchListings = Callable[[str], list]

SourceType = Literal[
    "direct_scraper",
    "generic_html",
    "rss",
    "sitemap",
    "manual",
    "partner",
    "api",
]


@dataclass
class RentalSource:
    source_key: str
    display_name: str
    enabled: bool
    supports_city_search: bool
    base_url: str
    notes: str
    fetch_listings: FetchListings
    category: str = "marketplace"
    manual_search_url_template: str | None = None
    auto_scan_enabled: bool = False
    scan_interval_minutes: int | None = None
    status: str = "manual"
    internal_reason: str | None = None
    max_timeout_seconds: int | None = None
    failure_count: int = 0
    last_scan_started_at: datetime | None = None
    last_scan_finished_at: datetime | None = None
    last_success_at: datetime | None = None
    last_error: str | None = None
    listings_found_last_scan: int = 0
    supports_automatic_scraping: bool = True
    status_note_nl: str | None = None
    status_note_en: str | None = None
    country: str = "NL"
    source_type: SourceType = "manual"
    supported_cities: tuple[str, ...] | None = None
    supports_price_filter: bool = False
    supports_property_type: bool = False
    supports_pagination: bool = False
    requires_detail_page: bool = False
    likely_blocks_bots: bool = False
    requires_login: bool = False
    supported_regions: tuple[str, ...] | None = None
    respect_notes: str | None = None
    priority: int = 50
    reliability_weight: float = 0.7

    @property
    def source_id(self) -> str:
        return self.source_key

    @property
    def default_enabled_for_auto_scan(self) -> bool:
        return self.auto_scan_enabled

    @property
    def interval_minutes(self) -> int:
        return self.scan_interval_minutes or settings.listing_scan_interval_minutes

    @property
    def timeout_seconds(self) -> int:
        return self.max_timeout_seconds or settings.listing_source_timeout_seconds

    def stagger_seconds(self) -> int:
        digest = hashlib.sha1(self.source_key.encode("utf-8")).hexdigest()
        return int(digest[:4], 16) % max(60, self.interval_minutes * 60)

    def next_due_at(self) -> datetime | None:
        if not self.auto_scan_enabled:
            return None

        if self.last_scan_finished_at is None:
            return None

        backoff_minutes = 0
        if self.failure_count:
            backoff_minutes = min(240, self.interval_minutes * (2 ** min(self.failure_count, 5)))

        interval = max(self.interval_minutes, backoff_minutes)
        return self.last_scan_finished_at + timedelta(minutes=interval, seconds=self.stagger_seconds())

    def manual_search_url(self, city: str | None = None) -> str | None:
        if not self.manual_search_url_template:
            return None

        normalized_city = quote("-".join((city or "").lower().split()))
        if not normalized_city:
            return None

        return self.manual_search_url_template.format(city=normalized_city)


def generic_fetcher(config: GenericSourceConfig) -> FetchListings:
    return lambda city: fetch_generic_source_listings(config, city=city)


def manual_only_fetcher() -> FetchListings:
    return lambda city: []


def make_generic_source(
    *,
    source_key: str,
    display_name: str,
    base_url: str,
    search_url_template: str,
    listing_path_markers: tuple[str, ...],
    blocked_markers: tuple[str, ...] = (),
    category: str = "marketplace",
    notes: str = "",
    auto_scan_enabled: bool = False,
    scan_interval_minutes: int | None = None,
    status: str = "limited",
    internal_reason: str | None = None,
    status_note_nl: str | None = None,
    status_note_en: str | None = None,
    likely_blocks_bots: bool = False,
    supports_pagination: bool = False,
    requires_detail_page: bool = False,
    priority: int = 50,
    reliability_weight: float = 0.6,
    supported_cities: tuple[str, ...] | None = None,
    supported_regions: tuple[str, ...] | None = None,
    requires_login: bool = False,
) -> RentalSource:
    """Build a generic-html RentalSource without repeating boilerplate."""
    config = GenericSourceConfig(
        source_id=source_key,
        display_name=display_name,
        search_url_template=search_url_template,
        listing_path_markers=listing_path_markers,
        blocked_markers=blocked_markers,
    )
    manual_template = search_url_template
    return RentalSource(
        source_key=source_key,
        display_name=display_name,
        enabled=True,
        supports_city_search=True,
        base_url=base_url,
        notes=notes or f"Public {display_name} rental search.",
        fetch_listings=generic_fetcher(config),
        category=category,
        manual_search_url_template=manual_template,
        auto_scan_enabled=auto_scan_enabled,
        scan_interval_minutes=scan_interval_minutes,
        status=status if not auto_scan_enabled else (status if status not in {"manual"} else "online"),
        internal_reason=internal_reason,
        supports_automatic_scraping=True,
        status_note_nl=status_note_nl,
        status_note_en=status_note_en,
        country="NL",
        source_type="generic_html",
        supports_price_filter=False,
        supports_property_type=False,
        supports_pagination=supports_pagination,
        requires_detail_page=requires_detail_page,
        likely_blocks_bots=likely_blocks_bots,
        requires_login=requires_login,
        priority=priority,
        reliability_weight=reliability_weight,
        supported_cities=supported_cities,
        supported_regions=supported_regions,
    )


def make_manual_source(
    *,
    source_key: str,
    display_name: str,
    base_url: str,
    manual_search_url_template: str,
    category: str = "housing-corporation",
    notes: str = "",
    internal_reason: str | None = None,
    status_note_nl: str | None = None,
    status_note_en: str | None = None,
    supported_cities: tuple[str, ...] | None = None,
    supported_regions: tuple[str, ...] | None = None,
    requires_login: bool = False,
    source_type: SourceType = "manual",
    supports_price_filter: bool = False,
    supports_property_type: bool = False,
    priority: int = 30,
) -> RentalSource:
    """Build a manual-only RentalSource (no automatic scraping)."""
    return RentalSource(
        source_key=source_key,
        display_name=display_name,
        enabled=True,
        supports_city_search=True,
        base_url=base_url,
        notes=notes or f"{display_name} portal — manual only.",
        fetch_listings=manual_only_fetcher(),
        category=category,
        manual_search_url_template=manual_search_url_template,
        auto_scan_enabled=False,
        status="manual",
        internal_reason=internal_reason,
        supports_automatic_scraping=False,
        status_note_nl=status_note_nl,
        status_note_en=status_note_en,
        country="NL",
        source_type=source_type,
        supports_price_filter=supports_price_filter,
        supports_property_type=supports_property_type,
        requires_login=requires_login,
        priority=priority,
        reliability_weight=0.0,
        supported_cities=supported_cities,
        supported_regions=supported_regions,
    )


RENTAL_SOURCES: list[RentalSource] = [
    # ---------- Direct scrapers (custom parsers, automatic) ----------
    RentalSource(
        source_key="marktplaats",
        display_name="Marktplaats",
        enabled=True,
        supports_city_search=True,
        base_url="https://www.marktplaats.nl",
        notes="Custom Marktplaats rental search across multiple keyword templates.",
        fetch_listings=fetch_marktplaats_listings,
        manual_search_url_template="https://www.marktplaats.nl/q/{city}+huurwoning/",
        category="marketplace",
        auto_scan_enabled=True,
        scan_interval_minutes=5,
        status="online",
        country="NL",
        source_type="direct_scraper",
        supports_pagination=False,
        likely_blocks_bots=True,
        priority=95,
        reliability_weight=0.85,
    ),
    RentalSource(
        source_key="funda",
        display_name="Funda",
        enabled=True,
        supports_city_search=True,
        base_url="https://www.funda.nl",
        notes="Custom Funda rental search.",
        fetch_listings=fetch_funda_listings,
        manual_search_url_template="https://www.funda.nl/zoeken/huur/?selected_area=%5B%22{city}%22%5D",
        category="marketplace",
        auto_scan_enabled=True,
        scan_interval_minutes=5,
        status="online",
        country="NL",
        source_type="direct_scraper",
        likely_blocks_bots=True,
        priority=98,
        reliability_weight=0.92,
    ),
    RentalSource(
        source_key="ikwilhuren",
        display_name="Ik wil huren",
        enabled=True,
        supports_city_search=True,
        base_url="https://ikwilhuren.nu",
        notes="MVGM / Ik wil huren landlord portal with detail-page enrichment.",
        fetch_listings=fetch_ikwilhuren_listings,
        manual_search_url_template="https://ikwilhuren.nu/aanbod?gemeente={city}",
        category="landlord",
        auto_scan_enabled=True,
        scan_interval_minutes=5,
        status="online",
        country="NL",
        source_type="direct_scraper",
        requires_detail_page=True,
        priority=85,
        reliability_weight=0.85,
    ),

    # ---------- Existing generic-html sources ----------
    make_generic_source(
        source_key="pararius",
        display_name="Pararius",
        base_url="https://www.pararius.nl",
        search_url_template="https://www.pararius.nl/huurwoningen/{city}",
        listing_path_markers=("/appartement-te-huur/", "/huis-te-huur/", "/kamer-te-huur/"),
        category="marketplace",
        notes="Major Dutch rental listing aggregator; bot protection often present.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="Public listings exist, but automated requests are frequently blocked.",
        status_note_nl="Beperkt: kan automatische verzoeken blokkeren.",
        status_note_en="Limited: may block automated requests.",
        likely_blocks_bots=True,
        supports_pagination=True,
        priority=90,
        reliability_weight=0.55,
    ),
    make_generic_source(
        source_key="huurwoningen",
        display_name="Huurwoningen.nl",
        base_url="https://www.huurwoningen.nl",
        search_url_template="https://www.huurwoningen.nl/in/{city}/",
        listing_path_markers=("/huur/", "/in/"),
        category="marketplace",
        notes="Generic public city listing parser.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="Public pages exist, but automated parsing is unstable across cities.",
        status_note_nl="Beperkt: werkt meestal beter handmatig.",
        status_note_en="Limited: usually works better manually.",
        supports_pagination=True,
        priority=80,
        reliability_weight=0.55,
    ),
    make_generic_source(
        source_key="kamernet",
        display_name="Kamernet",
        base_url="https://kamernet.nl",
        search_url_template="https://kamernet.nl/huren/kamer-{city}",
        listing_path_markers=("/huren/", "/kamer-", "/studio-", "/appartement-"),
        blocked_markers=("log in", "sign in"),
        category="marketplace",
        notes="Student-room / room-rental marketplace. Many details require account access.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="Most details require account access; do not scrape account-only content.",
        status_note_nl="Beperkt: details kunnen accounttoegang vereisen.",
        status_note_en="Limited: details may require account access.",
        likely_blocks_bots=True,
        priority=70,
        reliability_weight=0.4,
    ),
    make_generic_source(
        source_key="rentola",
        display_name="Rentola",
        base_url="https://rentola.nl",
        search_url_template="https://rentola.nl/huurwoningen/{city}",
        listing_path_markers=("/huurwoningen/", "/woning/", "/appartement/"),
        category="aggregator",
        notes="Aggregator; can show login/paywall prompts.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="May show login/paywall prompts and is unreliable for unattended scans.",
        status_note_nl="Beperkt: kan login- of betaalmuren tonen.",
        status_note_en="Limited: may show login or paywall prompts.",
        priority=55,
        reliability_weight=0.4,
    ),
    make_generic_source(
        source_key="huurportaal",
        display_name="Huurportaal",
        base_url="https://www.huurportaal.nl",
        search_url_template="https://www.huurportaal.nl/huurwoningen/{city}",
        listing_path_markers=("/huurwoning/", "/huurwoningen/", "/woning/"),
        category="aggregator",
        notes="Generic public city listing parser.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="Public pages may block automated requests; keep manual until reliability is proven.",
        status_note_nl="Beperkt: kan automatische verzoeken blokkeren.",
        status_note_en="Limited: may block automated requests.",
        priority=55,
        reliability_weight=0.5,
    ),
    make_generic_source(
        source_key="directwonen",
        display_name="Direct Wonen",
        base_url="https://directwonen.nl",
        search_url_template="https://directwonen.nl/huurwoningen-huren/{city}",
        listing_path_markers=("/huurwoningen-huren/", "/huurwoning/"),
        category="marketplace",
        notes="Generic public city listing parser.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="Public search exists, but automatic parsing is not yet reliable.",
        status_note_nl="Beperkt: handmatig openen blijft beschikbaar.",
        status_note_en="Limited: manual opening remains available.",
        priority=60,
        reliability_weight=0.5,
    ),
    make_generic_source(
        source_key="huislijn",
        display_name="Huislijn",
        base_url="https://www.huislijn.nl",
        search_url_template="https://www.huislijn.nl/huurwoning/nederland/{city}",
        listing_path_markers=("/huurwoning/", "/woning/"),
        category="aggregator",
        notes="Generic public rental search parser.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="City pages vary and need further validation before unattended scanning.",
        status_note_nl="Beperkt: zoekpagina's kunnen per stad verschillen.",
        status_note_en="Limited: city search pages may vary.",
        priority=55,
        reliability_weight=0.5,
    ),
    make_generic_source(
        source_key="heimstaden",
        display_name="Heimstaden",
        base_url="https://heimstaden.com",
        search_url_template="https://heimstaden.com/nl/huurwoningen/?text={city}",
        listing_path_markers=("/nl/huurwoningen/", "/nl/projecten/"),
        category="landlord",
        notes="Heimstaden Dutch rental portfolio (large landlord).",
        auto_scan_enabled=True,
        scan_interval_minutes=15,
        status="online",
        priority=80,
        reliability_weight=0.75,
    ),
    make_generic_source(
        source_key="rotsvast",
        display_name="Rotsvast",
        base_url="https://www.rotsvast.nl",
        search_url_template="https://www.rotsvast.nl/huren/?search={city}",
        listing_path_markers=("/huren/", "/woning/", "/appartement/"),
        category="marketplace",
        notes="National rental network with many regional offices.",
        auto_scan_enabled=True,
        scan_interval_minutes=15,
        status="online",
        priority=80,
        reliability_weight=0.75,
    ),
    make_generic_source(
        source_key="interhouse",
        display_name="Interhouse",
        base_url="https://interhouse.nl",
        search_url_template="https://interhouse.nl/huurwoningen/?keyword={city}",
        listing_path_markers=("/huurwoningen/", "/woning/"),
        category="marketplace",
        notes="Interhouse rental network.",
        auto_scan_enabled=True,
        scan_interval_minutes=15,
        status="degraded",
        internal_reason="Public listings exist, but the results UI is dynamic; monitor scan quality.",
        priority=70,
        reliability_weight=0.6,
    ),
    make_generic_source(
        source_key="maxx_aanhuur",
        display_name="Maxx Aanhuur",
        base_url="https://maxx-rental.com",
        search_url_template="https://maxx-rental.com/woningaanbod/?location={city}",
        listing_path_markers=("/woningaanbod/", "/aanbod/", "/huurwoning/"),
        category="marketplace",
        notes="Maxx Aanhuur rental offer page.",
        auto_scan_enabled=True,
        scan_interval_minutes=15,
        status="degraded",
        internal_reason="Public offer is visible, but the result loader can fail; monitor before promoting.",
        priority=70,
        reliability_weight=0.6,
    ),
    make_generic_source(
        source_key="vesteda",
        display_name="Vesteda",
        base_url="https://www.vesteda.com",
        search_url_template="https://www.vesteda.com/nl/huurwoningen-{city}",
        listing_path_markers=("/nl/huurwoningen-", "/woning/", "/aanbod/"),
        category="landlord",
        notes="Vesteda institutional residential landlord.",
        auto_scan_enabled=True,
        scan_interval_minutes=20,
        status="online",
        priority=80,
        reliability_weight=0.7,
    ),
    make_generic_source(
        source_key="holland2stay",
        display_name="Holland2Stay",
        base_url="https://www.holland2stay.com",
        search_url_template="https://www.holland2stay.com/residences?city={city}",
        listing_path_markers=("/residences/", "/residence/"),
        category="landlord",
        notes="Holland2Stay expat-focused landlord.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="Availability is app-driven and needs endpoint validation; do not scrape booking flows.",
        priority=70,
        reliability_weight=0.45,
    ),

    # ---------- New generic-html candidates (limited until validated) ----------
    make_generic_source(
        source_key="123wonen",
        display_name="123Wonen",
        base_url="https://www.123wonen.nl",
        search_url_template="https://www.123wonen.nl/huurwoningen/in/{city}",
        listing_path_markers=("/huurwoningen/", "/woning/", "/object/"),
        category="marketplace",
        notes="123Wonen national rental network with many regional branches.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="New candidate; will be enabled once listings parsing is validated.",
        priority=70,
        reliability_weight=0.55,
    ),
    make_generic_source(
        source_key="nederwoon",
        display_name="Nederwoon",
        base_url="https://www.nederwoon.nl",
        search_url_template="https://www.nederwoon.nl/aanbod/{city}",
        listing_path_markers=("/aanbod/", "/woning/", "/huurwoning/"),
        category="landlord",
        notes="Nederwoon (large institutional landlord).",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="New candidate; pending validation.",
        priority=75,
        reliability_weight=0.55,
    ),
    make_generic_source(
        source_key="pandomo",
        display_name="Pandomo",
        base_url="https://www.pandomo.nl",
        search_url_template="https://www.pandomo.nl/woningen/?plaats={city}",
        listing_path_markers=("/woningen/", "/woning/"),
        category="marketplace",
        notes="Pandomo property manager / rental network.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="New candidate; pending validation.",
        priority=60,
        reliability_weight=0.5,
    ),
    make_generic_source(
        source_key="friendly_housing",
        display_name="Friendly Housing",
        base_url="https://www.friendlyhousing.nl",
        search_url_template="https://www.friendlyhousing.nl/aanbod?location={city}",
        listing_path_markers=("/aanbod/", "/woning/"),
        category="landlord",
        notes="Friendly Housing (Eindhoven area) expat-focused rentals.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="New candidate; regional Eindhoven focus, pending validation.",
        priority=55,
        reliability_weight=0.5,
        supported_cities=("Eindhoven", "Helmond", "Veldhoven", "Geldrop"),
    ),
    make_generic_source(
        source_key="acasa",
        display_name="Acasa",
        base_url="https://www.acasa.nl",
        search_url_template="https://www.acasa.nl/aanbod/?location={city}",
        listing_path_markers=("/aanbod/", "/woning/"),
        category="marketplace",
        notes="Acasa rental network.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="New candidate; pending validation.",
        priority=55,
        reliability_weight=0.5,
    ),
    make_generic_source(
        source_key="expat_rentals",
        display_name="Expat Rentals NL",
        base_url="https://www.expatrentals.eu",
        search_url_template="https://www.expatrentals.eu/country/netherlands/{city}",
        listing_path_markers=("/country/netherlands/", "/property/"),
        category="marketplace",
        notes="Expat-focused rental aggregator (NL country pages).",
        auto_scan_enabled=True,
        scan_interval_minutes=20,
        status="online",
        priority=55,
        reliability_weight=0.65,
    ),
    make_generic_source(
        source_key="rentcompany",
        display_name="Rent Company",
        base_url="https://www.rentcompany.nl",
        search_url_template="https://www.rentcompany.nl/woningen-te-huur/?city={city}",
        listing_path_markers=("/woningen-te-huur/", "/woning/"),
        category="marketplace",
        notes="Rent Company national rental network.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="New candidate; pending validation.",
        priority=55,
        reliability_weight=0.5,
    ),
    make_generic_source(
        source_key="ymere_huur",
        display_name="Ymere (huur)",
        base_url="https://www.ymere.nl",
        search_url_template="https://www.ymere.nl/aanbod/?city={city}",
        listing_path_markers=("/aanbod/", "/woning/"),
        category="housing-corporation",
        notes="Ymere is a large housing corporation around Amsterdam.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="Most listings are passend aanbod (registration-only).",
        priority=40,
        reliability_weight=0.3,
        supported_cities=("Amsterdam", "Almere", "Haarlem", "Haarlemmermeer"),
    ),
    make_generic_source(
        source_key="duwo",
        display_name="DUWO",
        base_url="https://www.duwo.nl",
        search_url_template="https://www.duwo.nl/en/find-housing?city={city}",
        listing_path_markers=("/find-housing/", "/woning/", "/property/"),
        category="housing-corporation",
        notes="DUWO student housing corporation.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="Student housing; eligibility requires student status.",
        priority=45,
        reliability_weight=0.4,
    ),
    make_generic_source(
        source_key="xior",
        display_name="Xior Student Housing",
        base_url="https://www.xior.nl",
        search_url_template="https://www.xior.nl/aanbod?city={city}",
        listing_path_markers=("/aanbod/", "/residence/"),
        category="landlord",
        notes="Xior student housing (commercial student rentals).",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="New candidate; student-housing focus, pending validation.",
        priority=50,
        reliability_weight=0.45,
    ),
    make_generic_source(
        source_key="sshxl",
        display_name="SSH XL",
        base_url="https://www.sshxl.nl",
        search_url_template="https://www.sshxl.nl/en/listings?city={city}",
        listing_path_markers=("/listings/", "/residence/", "/woning/"),
        category="housing-corporation",
        notes="SSH (Stichting Studenten Huisvesting) student housing.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="Student housing; access can require registration.",
        priority=45,
        reliability_weight=0.4,
    ),
    make_generic_source(
        source_key="eervast",
        display_name="Eervast",
        base_url="https://www.eervast.nl",
        search_url_template="https://www.eervast.nl/woningaanbod?city={city}",
        listing_path_markers=("/woningaanbod/", "/woning/", "/object/"),
        category="marketplace",
        notes="Eervast property manager (regional).",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="New candidate; pending validation.",
        priority=45,
        reliability_weight=0.45,
    ),
    make_generic_source(
        source_key="rotsvast_breda",
        display_name="Rotsvast Breda",
        base_url="https://www.rotsvast.nl",
        search_url_template="https://www.rotsvast.nl/huren/?vestiging=breda&search={city}",
        listing_path_markers=("/huren/", "/woning/"),
        category="marketplace",
        notes="Rotsvast Breda branch (regional alias).",
        auto_scan_enabled=False,
        status="manual",
        internal_reason="Duplicate of national rotsvast — kept as manual link, not auto-scanned to avoid double-scraping.",
        priority=20,
        reliability_weight=0.3,
        supported_cities=("Breda", "Tilburg", "Oosterhout", "Etten-Leur"),
    ),
    make_generic_source(
        source_key="vbt_verhuurmakelaars",
        display_name="VBT Verhuurmakelaars",
        base_url="https://www.vbtverhuurmakelaars.nl",
        search_url_template="https://www.vbtverhuurmakelaars.nl/aanbod?location={city}",
        listing_path_markers=("/aanbod/", "/woning/"),
        category="marketplace",
        notes="VBT Verhuurmakelaars rental network.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="New candidate; pending validation.",
        priority=55,
        reliability_weight=0.5,
    ),
    make_generic_source(
        source_key="domica",
        display_name="Domica",
        base_url="https://www.domica.nl",
        search_url_template="https://www.domica.nl/aanbod?location={city}",
        listing_path_markers=("/aanbod/", "/woning/"),
        category="marketplace",
        notes="Domica rental and management network.",
        auto_scan_enabled=False,
        status="limited",
        internal_reason="New candidate; pending validation.",
        priority=50,
        reliability_weight=0.5,
    ),

    # ---------- Manual-only listings (housing corporations, paid platforms) ----------
    make_manual_source(
        source_key="huren_in_holland_rijnland",
        display_name="Huren in Holland Rijnland",
        base_url="https://www.hureninhollandrijnland.nl",
        manual_search_url_template="https://www.hureninhollandrijnland.nl/aanbod",
        notes="Regional housing-corporation portal (Holland-Rijnland).",
        internal_reason="Passend aanbod / responding require registration and household data.",
        supported_cities=("Leiden", "Alphen aan den Rijn", "Katwijk", "Voorschoten"),
    ),
    make_manual_source(
        source_key="thuispoort",
        display_name="Thuispoort",
        base_url="https://www.thuispoort.nl",
        manual_search_url_template="https://www.thuispoort.nl/aanbod",
        notes="Regional housing-corporation portal.",
        internal_reason="Passend aanbod / responding require registration / income context.",
    ),
    make_manual_source(
        source_key="woninghuren",
        display_name="WoningHuren.nl",
        base_url="https://www.woninghuren.nl",
        manual_search_url_template="https://www.woninghuren.nl/app/onboarding-1/passend-aanbod",
        notes="Housing-corporation portal (WoningHuren).",
        internal_reason="Passend aanbod / responding require account and income context.",
    ),
    make_manual_source(
        source_key="woning_in_zicht",
        display_name="Woning in Zicht",
        base_url="https://www.woninginzicht.nl",
        manual_search_url_template="https://www.woninginzicht.nl/aanbod",
        notes="Regional housing-corporation portal.",
        internal_reason="Social housing portal; account/passend-aanbod flow.",
    ),
    make_manual_source(
        source_key="nmg_wonen",
        display_name="NMG Wonen",
        base_url="https://nmgwonen.nl",
        manual_search_url_template="https://nmgwonen.nl/huur/",
        category="marketplace",
        notes="NMG Wonen offer page; stable listing endpoints not yet confirmed.",
        internal_reason="Listing endpoints not validated yet; manual link only.",
    ),
    make_manual_source(
        source_key="woonhave",
        display_name="Woonhave / Wonen.nu",
        base_url="https://wonen.nu",
        manual_search_url_template="https://wonen.nu/woningen?plaats={city}",
        category="landlord",
        notes="Woonhave offer is published via Wonen.nu.",
        internal_reason="Listing endpoint validation pending.",
    ),
    make_manual_source(
        source_key="woonzorg_nederland",
        display_name="Woonzorg Nederland",
        base_url="https://woningaanbod.woonzorg.nl",
        manual_search_url_template="https://woningaanbod.woonzorg.nl/",
        notes="Senior housing offer; some listings via local portals.",
        internal_reason="Senior-housing focus; partly redirects to local portals.",
    ),
    make_manual_source(
        source_key="huurstunt",
        display_name="Huurstunt",
        base_url="https://www.huurstunt.nl",
        manual_search_url_template="https://www.huurstunt.nl/",
        category="aggregator",
        notes="Paid aggregator/match service.",
        internal_reason="Paid match service; do not scrape premium/account-only listings.",
    ),
    make_manual_source(
        source_key="stekkies",
        display_name="Stekkies",
        base_url="https://www.stekkies.com",
        manual_search_url_template="https://www.stekkies.com/nl/zoeken",
        category="aggregator",
        notes="Paid aggregator/match service.",
        internal_reason="Paid search service; do not scrape account-only matches.",
    ),
    make_manual_source(
        source_key="woonbedrijf",
        display_name="Woonbedrijf",
        base_url="https://www.woonbedrijf.com",
        manual_search_url_template="https://www.woonbedrijf.com/aanbod",
        notes="Eindhoven-region social housing corporation.",
        internal_reason="Social housing; passend aanbod requires registration.",
        supported_cities=("Eindhoven", "Veldhoven", "Geldrop"),
    ),
    make_manual_source(
        source_key="woonnetlimburg",
        display_name="Thuis in Limburg",
        base_url="https://www.thuisinlimburg.nl",
        manual_search_url_template="https://www.thuisinlimburg.nl/aanbod",
        notes="Regional Limburg housing-corporation portal.",
        internal_reason="Passend aanbod / registration required.",
        supported_cities=("Maastricht", "Heerlen", "Sittard", "Roermond", "Venlo"),
    ),
    make_manual_source(
        source_key="woningnet_amsterdam",
        display_name="WoningNet Amsterdam",
        base_url="https://www.woningnetregioamsterdam.nl",
        manual_search_url_template="https://www.woningnetregioamsterdam.nl/aanbod/woningen",
        notes="WoningNet Amsterdam housing portal.",
        internal_reason="Social housing; registration required for responding.",
        supported_cities=("Amsterdam", "Diemen", "Amstelveen"),
    ),
    make_manual_source(
        source_key="woningnet_utrecht",
        display_name="WoningNet Utrecht",
        base_url="https://www.woningnetregioutrecht.nl",
        manual_search_url_template="https://www.woningnetregioutrecht.nl/aanbod/woningen",
        notes="WoningNet Utrecht housing portal.",
        internal_reason="Social housing; registration required for responding.",
        supported_cities=("Utrecht", "Nieuwegein", "Houten", "Zeist"),
    ),
    make_manual_source(
        source_key="enserve",
        display_name="Enserve / Woonkans",
        base_url="https://www.enserve.nl",
        manual_search_url_template="https://www.enserve.nl/aanbod",
        notes="Regional housing portal.",
        internal_reason="Social housing portal; registration-based.",
    ),
    make_manual_source(
        source_key="woonnet_rijnmond",
        display_name="Woonnet Rijnmond",
        base_url="https://www.woonnetrijnmond.nl",
        manual_search_url_template="https://www.woonnetrijnmond.nl/aanbod",
        notes="Social and regulated rental portal for Rotterdam/Rijnmond housing corporations.",
        internal_reason="Responding requires registration/woonpas; keep external-only.",
        supported_cities=("Rotterdam", "Dordrecht", "Schiedam", "Vlaardingen", "Barendrecht"),
        supported_regions=("Zuid-Holland", "Randstad", "Rijnmond"),
        requires_login=True,
        supports_price_filter=True,
        supports_property_type=True,
        priority=72,
    ),
    make_manual_source(
        source_key="klikvoorwonen",
        display_name="Klik voor Wonen",
        base_url="https://www.klikvoorwonen.nl",
        manual_search_url_template="https://www.klikvoorwonen.nl/aanbod",
        notes="West-Brabant housing-corporation portal with current rental supply.",
        internal_reason="Registration and passend-aanbod context are required to respond.",
        supported_cities=("Breda", "Roosendaal", "Bergen op Zoom", "Etten-Leur", "Oosterhout", "Zevenbergen"),
        supported_regions=("Noord-Brabant", "West-Brabant"),
        requires_login=True,
        supports_price_filter=True,
        supports_property_type=True,
        priority=74,
    ),
    make_manual_source(
        source_key="wooniezie",
        display_name="Wooniezie",
        base_url="https://www.wooniezie.nl",
        manual_search_url_template="https://www.wooniezie.nl/aanbod/nu-te-huur/huurwoningen",
        notes="Eindhoven/Helmond region corporation portal for social rentals and related offer.",
        internal_reason="Registration and income/passend-toewijzen context are needed for responding.",
        supported_cities=("Eindhoven", "Helmond", "Veldhoven", "Geldrop", "Best", "Nuenen"),
        supported_regions=("Noord-Brabant", "Zuidoost-Brabant"),
        requires_login=True,
        supports_price_filter=True,
        supports_property_type=True,
        priority=72,
    ),
    make_manual_source(
        source_key="entree",
        display_name="Entree",
        base_url="https://www.entree.nu",
        manual_search_url_template="https://www.entree.nu/",
        notes="Arnhem-Nijmegen housing-corporation portal.",
        internal_reason="Most responding requires registration and WoonWens/passend-aanbod context.",
        supported_cities=("Arnhem", "Nijmegen", "Wijchen", "Duiven", "Zevenaar"),
        supported_regions=("Gelderland", "Arnhem-Nijmegen"),
        requires_login=True,
        supports_price_filter=True,
        supports_property_type=True,
        priority=70,
    ),
    make_manual_source(
        source_key="room_university_housing",
        display_name="ROOM University Housing",
        base_url="https://uh.room.nl",
        manual_search_url_template="https://uh.room.nl/",
        category="housing-corporation",
        notes="University housing platform for students/staff in several Dutch university cities.",
        internal_reason="Eligibility and booking availability depend on institution/account access.",
        supported_cities=("Amsterdam", "Delft", "Den Haag", "Leiden", "Haarlem", "Wageningen"),
        supported_regions=("Randstad", "Zuid-Holland", "Noord-Holland"),
        requires_login=True,
        priority=58,
    ),
    make_manual_source(
        source_key="plaza_newnewnew",
        display_name="Plaza Resident Services",
        base_url="https://plaza.newnewnew.space",
        manual_search_url_template="https://plaza.newnewnew.space/",
        category="landlord",
        notes="Student/young-professional residences and temporary housing locations.",
        internal_reason="Requires account for responding; availability is app-driven.",
        supported_cities=("Maastricht", "Amsterdam", "Utrecht", "Eindhoven", "Enschede", "Delft", "Breda", "Arnhem"),
        supported_regions=("Randstad", "Noord-Brabant", "Gelderland", "Limburg", "Overijssel"),
        requires_login=True,
        priority=57,
    ),
    make_manual_source(
        source_key="thuiskompas",
        display_name="Thuiskompas",
        base_url="https://www.thuiskompas.nl",
        manual_search_url_template="https://www.thuiskompas.nl/",
        notes="Corporation portal for Drenthe and surrounding areas.",
        internal_reason="Responding requires registration; outside core scan cities but useful for broader NL search.",
        supported_cities=("Assen", "Emmen", "Hoogeveen", "Meppel", "Stadskanaal"),
        supported_regions=("Drenthe", "Groningen"),
        requires_login=True,
        supports_price_filter=True,
        supports_property_type=True,
        priority=48,
    ),
    make_manual_source(
        source_key="dak_woningnet",
        display_name="DAK / WoningNet",
        base_url="https://www.dak.nl",
        manual_search_url_template="https://www.dak.nl/aanbod",
        notes="WoningNet/DAK route for social housing regions including Utrecht and Amsterdam.",
        internal_reason="Registration, local rules and income context are required.",
        supported_cities=("Amsterdam", "Utrecht", "Amstelveen", "Nieuwegein", "Houten", "Zeist"),
        supported_regions=("Randstad", "Noord-Holland", "Utrecht"),
        requires_login=True,
        supports_price_filter=True,
        supports_property_type=True,
        priority=68,
    ),
    make_manual_source(
        source_key="woonnet_haaglanden",
        display_name="Woonnet Haaglanden",
        base_url="https://www.woonnet-haaglanden.nl",
        manual_search_url_template="https://www.woonnet-haaglanden.nl/aanbod",
        notes="Housing-corporation portal for Den Haag and Haaglanden.",
        internal_reason="Registration and eligibility data required for responding.",
        supported_cities=("Den Haag", "Delft", "Zoetermeer", "Rijswijk", "Leidschendam-Voorburg"),
        supported_regions=("Zuid-Holland", "Randstad", "Haaglanden"),
        requires_login=True,
        supports_price_filter=True,
        supports_property_type=True,
        priority=70,
    ),
    make_manual_source(
        source_key="studentenwoningweb",
        display_name="Studentenwoningweb",
        base_url="https://www.studentenwoningweb.nl",
        manual_search_url_template="https://www.studentenwoningweb.nl/",
        category="housing-corporation",
        notes="Student housing portal for Amsterdam and nearby student markets.",
        internal_reason="Student eligibility and registration are required.",
        supported_cities=("Amsterdam", "Diemen", "Amstelveen"),
        supported_regions=("Noord-Holland", "Randstad"),
        requires_login=True,
        priority=55,
    ),
    make_manual_source(
        source_key="roomspot",
        display_name="Roomspot",
        base_url="https://www.roomspot.nl",
        manual_search_url_template="https://www.roomspot.nl/",
        category="housing-corporation",
        notes="Student housing platform for Twente and Wageningen-related supply.",
        internal_reason="Student registration/eligibility can be required.",
        supported_cities=("Enschede", "Wageningen", "Deventer", "Apeldoorn"),
        supported_regions=("Overijssel", "Gelderland"),
        requires_login=True,
        priority=50,
    ),
    make_manual_source(
        source_key="groningen_huurt",
        display_name="Groningen Huurt",
        base_url="https://www.groningenhuurt.nl",
        manual_search_url_template="https://www.groningenhuurt.nl/",
        notes="Regional corporation portal for Groningen rental housing.",
        internal_reason="Registration and local eligibility context required.",
        supported_cities=("Groningen", "Midden-Groningen", "Stadskanaal"),
        supported_regions=("Groningen"),
        requires_login=True,
        supports_price_filter=True,
        supports_property_type=True,
        priority=58,
    ),
    make_manual_source(
        source_key="woonkeus_stedendriehoek",
        display_name="Woonkeus Stedendriehoek",
        base_url="https://www.woonkeus-stedendriehoek.nl",
        manual_search_url_template="https://www.woonkeus-stedendriehoek.nl/aanbod",
        notes="Regional housing-corporation portal around Apeldoorn/Deventer/Zutphen.",
        internal_reason="Registration and passend-aanbod rules apply.",
        supported_cities=("Apeldoorn", "Deventer", "Zutphen"),
        supported_regions=("Gelderland", "Overijssel", "Stedendriehoek"),
        requires_login=True,
        supports_price_filter=True,
        priority=54,
    ),
    make_manual_source(
        source_key="huren_noord_veluwe",
        display_name="Huren Noord-Veluwe",
        base_url="https://www.hurennoordveluwe.nl",
        manual_search_url_template="https://www.hurennoordveluwe.nl/aanbod",
        notes="Regional housing-corporation portal for Noord-Veluwe.",
        internal_reason="Registration and local allocation rules apply.",
        supported_cities=("Apeldoorn", "Harderwijk", "Epe", "Nunspeet"),
        supported_regions=("Gelderland", "Noord-Veluwe"),
        requires_login=True,
        supports_price_filter=True,
        priority=47,
    ),
    make_manual_source(
        source_key="de_woningzoeker",
        display_name="De Woningzoeker",
        base_url="https://www.dewoningzoeker.nl",
        manual_search_url_template="https://www.dewoningzoeker.nl/aanbod",
        notes="Regional housing-corporation portal for parts of Flevoland and Noord-Holland.",
        internal_reason="Registration and allocation rules apply.",
        supported_cities=("Almere", "Lelystad", "Dronten"),
        supported_regions=("Flevoland", "Noord-Holland"),
        requires_login=True,
        supports_price_filter=True,
        priority=52,
    ),
    make_manual_source(
        source_key="liv_residential",
        display_name="LIV Residential",
        base_url="https://livresidential.nl",
        manual_search_url_template="https://livresidential.nl/woningen?city={city}",
        category="landlord",
        notes="Commercial rental platform with homes in major Dutch cities.",
        internal_reason="Public offer exists, but automated parsing has not been validated.",
        supported_cities=("Amsterdam", "Rotterdam", "Den Haag", "Utrecht", "Alkmaar"),
        supported_regions=("Randstad", "Noord-Holland", "Zuid-Holland", "Utrecht"),
        source_type="generic_html",
        supports_price_filter=True,
        supports_property_type=True,
        priority=64,
    ),
    make_manual_source(
        source_key="bwhousing",
        display_name="BW Housing",
        base_url="https://www.bwhousing.nl",
        manual_search_url_template="https://www.bwhousing.nl/rent-property?city={city}",
        category="marketplace",
        notes="Expat-focused rental agency for western Netherlands.",
        internal_reason="Manual external source until stable public listing parsing is validated.",
        supported_cities=("Den Haag", "Rotterdam", "Amsterdam", "Leiden", "Delft"),
        supported_regions=("Randstad", "Zuid-Holland", "Noord-Holland"),
        source_type="generic_html",
        priority=56,
    ),
    make_manual_source(
        source_key="tvn_real_estate",
        display_name="TVN Real Estate",
        base_url="https://www.tvnrealestate.nl",
        manual_search_url_template="https://www.tvnrealestate.nl/en/for-rent",
        category="marketplace",
        notes="Rental agency with furnished/short-stay homes in Amsterdam, Rotterdam, Den Haag and Utrecht.",
        internal_reason="Manual external source; short-stay/furnished offer should not be mixed into scraped results yet.",
        supported_cities=("Amsterdam", "Rotterdam", "Den Haag", "Utrecht"),
        supported_regions=("Randstad"),
        source_type="generic_html",
        priority=52,
    ),
    make_manual_source(
        source_key="housinganywhere",
        display_name="HousingAnywhere",
        base_url="https://housinganywhere.com",
        manual_search_url_template="https://housinganywhere.com/s/{city}--Netherlands",
        category="marketplace",
        notes="International rental marketplace with rooms, studios and apartments.",
        internal_reason="Account/application flows and anti-bot controls; use as external source only.",
        supported_cities=("Amsterdam", "Rotterdam", "Den Haag", "Utrecht", "Eindhoven", "Groningen", "Maastricht", "Leiden"),
        supported_regions=("Randstad", "Noord-Brabant", "Groningen", "Limburg"),
        requires_login=True,
        source_type="manual",
        priority=62,
    ),
    make_manual_source(
        source_key="the_fizz",
        display_name="The Fizz",
        base_url="https://www.the-fizz.com",
        manual_search_url_template="https://www.the-fizz.com/en/student-accommodation/netherlands/",
        category="landlord",
        notes="Student housing operator with Dutch residences.",
        internal_reason="Availability and applications are managed through provider flow; external-only.",
        supported_cities=("Amsterdam", "Utrecht", "Leiden"),
        supported_regions=("Randstad"),
        requires_login=True,
        priority=44,
    ),
    make_manual_source(
        source_key="camelot_europe",
        display_name="Camelot Europe",
        base_url="https://nl.cameloteurope.com",
        manual_search_url_template="https://nl.cameloteurope.com/aanbod",
        category="landlord",
        notes="Temporary and anti-squat housing provider; check terms carefully.",
        internal_reason="Temporary/anti-squat contracts need explicit user review; external-only.",
        supported_regions=("Nederland",),
        requires_login=True,
        priority=35,
    ),
]


LAST_SOURCE_RUNS: dict[str, dict] = {}


def enabled_sources(source_ids: list[str] | None = None, auto_only: bool = False) -> list[RentalSource]:
    if source_ids is None:
        return [
            source
            for source in RENTAL_SOURCES
            if source.enabled and (not auto_only or source.auto_scan_enabled)
        ]

    selected_ids = set(source_ids)
    return [
        source
        for source in RENTAL_SOURCES
        if source.enabled
        and source.source_id in selected_ids
        and (not auto_only or source.auto_scan_enabled)
    ]


def source_payload(source: RentalSource, city: str | None = None) -> dict:
    next_due_at = source.next_due_at()
    return {
        "source_id": source.source_key,
        "source_key": source.source_key,
        "display_name": source.display_name,
        "enabled": source.enabled,
        "supports_city_search": source.supports_city_search,
        "base_url": source.base_url,
        "category": source.category,
        "notes": source.notes,
        "internal_reason": source.internal_reason,
        "manual_search_url_template": source.manual_search_url_template,
        "manual_search_url": source.manual_search_url(city),
        "default_enabled_for_auto_scan": source.default_enabled_for_auto_scan,
        "auto_scan_enabled": source.auto_scan_enabled,
        "scan_interval_minutes": source.interval_minutes,
        "max_timeout_seconds": source.timeout_seconds,
        "status": source.status,
        "last_scan_started_at": source.last_scan_started_at.isoformat() if source.last_scan_started_at else None,
        "last_scan_finished_at": source.last_scan_finished_at.isoformat() if source.last_scan_finished_at else None,
        "last_success_at": source.last_success_at.isoformat() if source.last_success_at else None,
        "last_error": source.last_error,
        "last_failed_at": None,
        "last_failed_error": None,
        "listings_found_last_scan": source.listings_found_last_scan,
        "total_listing_count": 0,
        "active_listing_count": 0,
        "failure_count": source.failure_count,
        "next_due_at": next_due_at.isoformat() if next_due_at else None,
        "supports_automatic_scraping": source.supports_automatic_scraping,
        "status_note_nl": source.status_note_nl,
        "status_note_en": source.status_note_en,
        "country": source.country,
        "source_type": source.source_type,
        "supported_cities": list(source.supported_cities) if source.supported_cities else None,
        "supported_regions": list(source.supported_regions) if source.supported_regions else None,
        "requires_login": source.requires_login,
        "supports_price_filter": source.supports_price_filter,
        "supports_property_type": source.supports_property_type,
        "supports_pagination": source.supports_pagination,
        "requires_detail_page": source.requires_detail_page,
        "likely_blocks_bots": source.likely_blocks_bots,
        "priority": source.priority,
        "reliability_weight": source.reliability_weight,
        "last_run": LAST_SOURCE_RUNS.get(source.source_id),
    }
